---
  - name: Check netrc
    stat: path=/root/.netrc
    register: netrc_stat

  - name: Copy netrc to remote host
    copy: src=.netrc dest=/root/
    when: netrc_stat.stat.exists == False

  - name: Git clone
    shell: cd /usr/local/src/ && [[ -d deploy ]] || timeout 60 git clone http://122.11.50.228:9186/cdnzb/deploy.git
    register: clone

  - authorized_key: user=root state=present key="{{ lookup('file', '/root/.ssh/id_rsa.pub') }}" state=present
    when: clone.rc != 0

  - name: rsync clone fail
    synchronize: src=/etc/ansible/deploy/ dest=/usr/local/src/deploy/ rsync_opts=--delete
    when: clone.rc !=0 

  - name: Git pull
    command: chdir=/usr/local/src/deploy timeout 60 git pull
    register: pull

  - authorized_key: user=root state=present key="{{ lookup('file', '/root/.ssh/id_rsa.pub') }}" state=present
    when: pull.rc != 0

  - name: rsync pull fail
    synchronize: src=/etc/ansible/deploy/ dest=/usr/local/src/deploy/ rsync_opts=--delete
    when: pull.rc != 0

